/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autonoma.furiaenlacarretera.views;

import autonoma.furiaenlacarretera.elements.GameField;
import autonoma.furiaenlacarretera.elements.RefreshProgram;
import autonoma.furiaenlacarretera.sounds.ReproducirSonido;
import java.awt.Color;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Kamii
 */
public class Mapas extends JFrame {

    private String mapaSeleccionado;

    /**
     * Creates new form Mapas
     */
    public Mapas() {
        setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        ReproducirSonido.playSound("sonidoInicio.wav");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMapa = new javax.swing.JPanel();
        panelPlay = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelMapa1 = new javax.swing.JPanel();
        labelMapa1 = new javax.swing.JLabel();
        panelMapa2 = new javax.swing.JPanel();
        labelMapa2 = new javax.swing.JLabel();
        labelMapaFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMapa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPlay.setBackground(new java.awt.Color(0, 0, 0));
        panelPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPlayMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("PLAY!");

        javax.swing.GroupLayout panelPlayLayout = new javax.swing.GroupLayout(panelPlay);
        panelPlay.setLayout(panelPlayLayout);
        panelPlayLayout.setHorizontalGroup(
            panelPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPlayLayout.setVerticalGroup(
            panelPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelMapa.add(panelPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 250, 80, 30));

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setText("SELECCIONA UN MAPA");
        panelMapa.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 320, 30));

        panelMapa1.setBackground(new java.awt.Color(0, 0, 0));

        labelMapa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/furiaenlacarretera/images/Mapa1.jpg"))); // NOI18N
        labelMapa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMapa1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMapa1Layout = new javax.swing.GroupLayout(panelMapa1);
        panelMapa1.setLayout(panelMapa1Layout);
        panelMapa1Layout.setHorizontalGroup(
            panelMapa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMapa1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(labelMapa1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelMapa1Layout.setVerticalGroup(
            panelMapa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMapa1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMapa1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMapa.add(panelMapa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 170, -1));

        labelMapa2.setText("ddd");
        labelMapa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMapa2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMapa2Layout = new javax.swing.GroupLayout(panelMapa2);
        panelMapa2.setLayout(panelMapa2Layout);
        panelMapa2Layout.setHorizontalGroup(
            panelMapa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMapa2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMapa2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMapa2Layout.setVerticalGroup(
            panelMapa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMapa2Layout.createSequentialGroup()
                .addComponent(labelMapa2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelMapa.add(panelMapa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 120, 100));

        labelMapaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/furiaenlacarretera/images/LabelMapas.gif"))); // NOI18N
        labelMapaFondo.setToolTipText("");
        panelMapa.add(labelMapaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelMapa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMapa1MouseClicked
        mapaSeleccionado = "mapa.jpeg";
        Random rand = new Random();
        Color randomColor = new Color(0, 153, 51);
        panelMapa1.setBackground(randomColor);

    }//GEN-LAST:event_labelMapa1MouseClicked

    private void panelPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPlayMouseClicked
        if (mapaSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Primero selecciona un mapa");
            return;
        }
        iniciarJuego();
    }//GEN-LAST:event_panelPlayMouseClicked

    private void labelMapa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMapa2MouseClicked
        mapaSeleccionado = "mapa.jpeg";
        Random rand = new Random();
        Color randomColor = new Color(0, 153, 51);
        panelMapa1.setBackground(randomColor);
    }//GEN-LAST:event_labelMapa2MouseClicked
    /**
     * Este método inicializa y configura el juego al hacer clic en el botón
     * "JUGAR". Crea una nueva instancia de los objetos necesarios para iniciar
     * la partida, configura la ventana de juego y muestra el campo de batalla
     * con el jugador. Después de iniciar el juego, cierra la ventana de inicio.
     */
    private void iniciarJuego() {
        ReproducirSonido.detener();
        this.dispose();
        GameField gameField = new GameField(0, 0, 500, 500, mapaSeleccionado);
        gameField.addJugador();

        GameWindow window = new GameWindow(gameField);
        gameField.setGraphicContainer(window);

        window.setSize(500, 500);
        window.setTitle("Furia en la carretera");
        window.setLocationRelativeTo(null);
        window.setVisible(true);
        RefreshProgram gameLoop = new RefreshProgram(gameField, window);
        gameLoop.start();

        this.dispose();
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelMapa1;
    private javax.swing.JLabel labelMapa2;
    private javax.swing.JLabel labelMapaFondo;
    private javax.swing.JPanel panelMapa;
    private javax.swing.JPanel panelMapa1;
    private javax.swing.JPanel panelMapa2;
    private javax.swing.JPanel panelPlay;
    // End of variables declaration//GEN-END:variables
}
