package autonoma.furiaenlacarretera.views;

import autonoma.furiaenlacarretera.elements.GameField;
import autonoma.furiaenlacarretera.elements.RefreshProgram;
import autonoma.furiaenlacarretera.sounds.ReproducirSonido;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Kamii
 */
public class VentanaInicial extends JFrame {

    /**
     * Creates new form VentanaInicial
     */
    public VentanaInicial() {
        setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        ReproducirSonido.playSound("sonidoInicio.wav");

        try {
            this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/furiaenlacarretera/images/carroBugatti.png")).getImage());
        } catch (Exception e) {
            System.out.println("imagen no encontrada");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelPlay = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        imgPirncipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(48, 194, 2));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        panelPrincipal.setBackground(new java.awt.Color(20, 0, 16));
        panelPrincipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelPrincipalKeyPressed(evt);
            }
        });
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPlay.setBackground(new java.awt.Color(201, 88, 105));
        panelPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPlayMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(201, 88, 105));
        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel1.setText("PLAY!");

        javax.swing.GroupLayout panelPlayLayout = new javax.swing.GroupLayout(panelPlay);
        panelPlay.setLayout(panelPlayLayout);
        panelPlayLayout.setHorizontalGroup(
            panelPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPlayLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelPlayLayout.setVerticalGroup(
            panelPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPlayLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        panelPrincipal.add(panelPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        imgPirncipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/furiaenlacarretera/images/furia_en_la_carretera_500px.gif"))); // NOI18N
        panelPrincipal.add(imgPirncipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPlayMouseClicked
        iniciarJuego();
    }//GEN-LAST:event_panelPlayMouseClicked

    private void panelPrincipalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelPrincipalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_Q) {
            System.exit(0);
        }
    }//GEN-LAST:event_panelPrincipalKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_Q) {
            System.exit(0);
        }
    }//GEN-LAST:event_formKeyPressed
    /**
     * Este método inicializa y configura el juego al hacer clic en el botón
     * "JUGAR". Crea una nueva instancia de los objetos necesarios para iniciar
     * la partida, configura la ventana de juego y muestra el campo de batalla
     * con el jugador. Después de iniciar el juego, cierra la ventana de inicio.
     */
    private void iniciarJuego() {
        ReproducirSonido.detener();
        this.dispose();
        GameField gameField = new GameField(0, 0, 500, 500);
        gameField.addJugador();

        //Player player = new Player(armaInicial, 100, 100, 50, 50);
        //gameField.setPlayer(player);
        GameWindow window = new GameWindow(gameField);
        gameField.setGraphicContainer(window);

        window.setSize(500, 500);
        window.setTitle("Furia en la carretera");
        window.setLocationRelativeTo(null);
        window.setVisible(true);
        RefreshProgram gameLoop = new RefreshProgram(gameField, window);
        gameLoop.start();

        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgPirncipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelPlay;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
